apiVersion: v1
kind: Service
metadata:
  name: redis               # Vote App и Worker ищут Redis по DNS-имени "redis"
  namespace: voting
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
