apiVersion: v1
kind: Service
metadata:
  name: db                 # Worker и Result ищут БД по DNS-имени "db"
  namespace: voting
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
